backend:
  name: github
  repo: chrisgeary92/netlify-cms-editor-issue
  branch: master

media_folder: "cms"

collections:

  - name: "example"
    label: "Example"
    files:
      - name: "example"
        label: "Example"
        file: "example.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
